name: Build and Deploy Docker Image to Azure Web App

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Azure Container Registry
        run: |
          echo ${{ secrets.ACR_PASSWORD }} | docker login ${{ secrets.ACR_LOGIN_SERVER }} -u ${{ secrets.ACR_USERNAME }} --password-stdin

      - name: Build and push Docker image
        run: |
          docker build -t ${{ secrets.ACR_LOGIN_SERVER }}/your-api-image:latest .
          docker push ${{ secrets.ACR_LOGIN_SERVER }}/your-api-image:latest

      - name: Deploy to Azure Web App for Containers
        uses: azure/webapps-deploy@v2
        with:
          app-name: "your-azure-web-app-name"
          images: "${{ secrets.ACR_LOGIN_SERVER }}/your-api-image:latest"
          azure-rm-service-principal: ${{ secrets.AZURE_CLIENT_ID }}
          azure-rm-tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          azure-rm-subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          azure-rm-client-secret: ${{ secrets.AZURE_CLIENT_SECRET }}
